"""MapperAgentActivity — run the Mapper AI agent to generate a bank's map.json.

PLACEHOLDER — wired in task 14 (MapBankWorkflow + MapperAgent).

Retry policy (orchestrator.md §Inventario):
  - NO retry (expensive LLM call — sin retry).
  - start-to-close timeout: 20 min.
  - Heartbeat every 30 s, reporting each explored step.

Idempotency key: bank_id + run_id.

Uses Claude Sonnet 4.6 vision to generate the map.json declarative navigation
definition (Mapper-Runner split architecture per CLAUDE.md).

Cost guardrail: aborts with ApplicationError(non_retryable=True) if $0.50/job
LLM budget is exceeded.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from temporalio import activity


class BankMap(BaseModel):
    """Declarative bank navigation map generated by the Mapper agent.

    Opaque structure at this stage — schema defined in task 14.
    """

    bank_id: str = Field(description="Bank identifier")
    version: str = Field(description="Semver map version (e.g. '1.0.0')")
    steps: list[dict[str, object]] = Field(
        default_factory=list,
        description="Navigation step definitions (schema TBD in task 14)",
    )
    generated_at: str = Field(description="ISO 8601 UTC timestamp of map generation")


class MapperAgentInput(BaseModel):
    """Input for MapperAgentActivity."""

    job_id: str = Field(description="Parent job identifier")
    bank_id: str = Field(description="Bank to map")
    run_id: str = Field(description="Unique run ID for idempotency (bank_id + run_id)")
    sandbox_container_id: str = Field(
        description="Sandbox container with live browser for visual exploration"
    )
    llm_budget_usd: float = Field(
        default=0.50,
        description="Maximum LLM spend allowed for this mapping run",
    )


class MapperAgentResult(BaseModel):
    """Result from MapperAgentActivity."""

    bank_map: BankMap = Field(description="Generated declarative navigation map")
    llm_cost_usd: float = Field(description="Actual LLM spend for this run")
    steps_explored: int = Field(description="Number of navigation steps explored")


class MapperAgentActivity:
    """MapperAgentActivity class-based wrapper."""


@activity.defn(name="MapperAgentActivity")
async def mapper_agent(input: MapperAgentInput) -> MapperAgentResult:
    """Run the Mapper agent to generate map.json for a bank.

    PLACEHOLDER — wired in task 14 (MapBankWorkflow + MapperAgent).

    Sends heartbeats every 30 s reporting the current exploration step.

    TODO: integrate with PydanticAI + Claude Sonnet 4.6 vision (task 14).
    TODO: enforce LLM cost budget guardrail (abort if budget exceeded).
    TODO: call activity.heartbeat(step=step_name, explored=N) every 30 s.
    TODO: persist generated map.json to storage (cosign-signed community map).
    """
    raise NotImplementedError("MapperAgentActivity not implemented — PLACEHOLDER, wired in task 14")
